# ============================================================================
# nrm_county_analysis.jl
#
# Compare NBPopulationRatesMarg / NBPopulationRates and
# PoissonPopulationRatesMarg / PoissonPopulationRates under several RJMCMC
# proposal combinations on the UK National Referral Mechanism (NRM) Q3 2025
# county-level dataset.
#
# Data source: data/nrm_county_data.csv (generated by prepare_nrm_county_data.py)
#   74 UK historic counties with referral counts + population denominators
#   and five deprivation domain covariates (IMD/WIMD/SIMD/NIMDM, normalised).
#
# Usage:
#   julia --project scripts/nrm_county_analysis.jl           # full run
#   julia --project scripts/nrm_county_analysis.jl --test    # 200 iterations
# ============================================================================

using DDCRP
using CSV, DataFrames, Distances
using Statistics, StatsBase, LinearAlgebra
using Random
using Printf
using JLD2
using StatsPlots, Plots

Random.seed!(42)

# ============================================================================
# Load data
# ============================================================================

data_path = joinpath(dirname(@__DIR__), "data", "nrm_county_data.csv")
df = CSV.read(data_path, DataFrame)

y = Int.(df.referrals)          # fully observed — no missing
P = Int.(df.population)

covariate_cols = [:income, :employment, :education, :health, :crime]
X     = Float64.(Matrix(df[:, covariate_cols]))
X_std = (X .- mean(X, dims=1)) ./ std(X, dims=1)
D     = pairwise(Euclidean(), X_std', dims=2)
n     = length(y)

@printf("Dataset: %d counties, referrals %d–%d, population %d–%d\n",
        n, minimum(y), maximum(y), minimum(P), maximum(P))

# ============================================================================
# Shared settings
# ============================================================================

test_mode = "--test" in ARGS
if test_mode
    println("Running in test mode (small iteration count).")
end

ddcrp_params = DDCRPParams(1.0, 1.0, 1.0, 0.1, 1.0, 0.1)

# NB priors
γ_a, γ_b = 1.0, 0.5
r_a, r_b  = 2.0, 0.5
# Poisson priors
ρ_a, ρ_b  = 1.0, 1.0

n_samples = test_mode ? 200 : 100_000
burn      = div(n_samples, 5)

base_opts = MCMCOptions(
    n_samples    = n_samples,
    verbose      = false,
    infer_params = Dict(
        :s_ddcrp  => false,
        :r        => false,
        :α_ddcrp  => true,
    ),
)

# ============================================================================
# Define proposals
# ============================================================================

proposals = [
    # --- Negative Binomial ---
    (
        label     = "NB Marg (Gibbs)",
        model     = NBPopulationRatesMarg(),
        priors    = NBPopulationRatesMargPriors(γ_a, γ_b, r_a, r_b),
        birth     = ConjugateProposal(),
        fixed_dim = NoUpdate(),
    ),
    (
        label     = "NB Prior + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = PriorProposal(),
        fixed_dim = Resample(PriorProposal()),
    ),
    (
        label     = "NB LogNormalMM + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = LogNormalMomentMatch(1.0),
        fixed_dim = Resample(PriorProposal()),
    ),
    (
        label     = "NB IGammaMM + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = InverseGammaMomentMatch(),
        fixed_dim = Resample(PriorProposal()),
    ),
    # --- Poisson ---
    (
        label     = "Pois Marg (Gibbs)",
        model     = PoissonPopulationRatesMarg(),
        priors    = PoissonPopulationRatesMargPriors(ρ_a, ρ_b),
        birth     = ConjugateProposal(),
        fixed_dim = NoUpdate(),
    ),
    (
        label     = "Pois Prior + Resample",
        model     = PoissonPopulationRates(),
        priors    = PoissonPopulationRatesPriors(ρ_a, ρ_b),
        birth     = PriorProposal(),
        fixed_dim = Resample(PriorProposal()),
    ),
]

# ============================================================================
# Run all proposals
# ============================================================================

results = []

for prop in proposals
    println("\n--- $(prop.label) ---")
    flush(stdout)

    samples, _ = mcmc(prop.model, y, P, D, ddcrp_params, prop.priors, prop.birth;
                      fixed_dim_proposal=prop.fixed_dim, opts=base_opts)

    k_post = calculate_n_clusters(samples.c[(burn+1):end, :])
    push!(results, (label=prop.label, k=k_post, samples=samples))
end

# ============================================================================
# Print posterior P(K) table
# ============================================================================

k_all = sort(unique(vcat([r.k for r in results]...)))

println("\n")
println("=== Posterior P(K) by proposal ===")
println()

k_cols    = join([@sprintf("  K=%-3d", k) for k in k_all])
col_header = @sprintf("%-32s", "Proposal") * k_cols * @sprintf("  %s  %s", "Mean K", "Mode K")
println(col_header)
println(repeat("-", length(col_header)))

for r in results
    k_probs = join([@sprintf("  %-5.3f", mean(r.k .== k)) for k in k_all])
    println(@sprintf("%-32s", r.label) * k_probs *
            @sprintf("  %-6.2f  %-6d", mean(r.k), mode(r.k)))
end

# ============================================================================
# Plot: posterior P(K) for NB and Poisson separately + K trace plots
# ============================================================================

nb_results   = filter(r -> startswith(r.label, "NB"),   results)
pois_results = filter(r -> startswith(r.label, "Pois"), results)

nb_colors   = [:black, :steelblue, :darkorange, :forestgreen]
pois_colors = [:black, :steelblue]
nb_styles   = [:solid, :dash, :dash, :dash]
pois_styles = [:solid, :dash]

# P(K) — NB
p_nb_k = plot(
    title  = "Posterior P(K) — NB models\n(NRM Q3 2025, n=$n counties)",
    xlabel = "Number of clusters K",
    ylabel = "Posterior probability",
    legend = :topright,
    xticks = k_all,
)
for (i, r) in enumerate(nb_results)
    p_k = [mean(r.k .== k) for k in k_all]
    plot!(p_nb_k, k_all, p_k;
          label=r.label, color=nb_colors[i], linestyle=nb_styles[i],
          linewidth=(i==1 ? 3 : 1.5), marker=:circle, markersize=4)
end

# P(K) — Poisson
p_pois_k = plot(
    title  = "Posterior P(K) — Poisson models\n(NRM Q3 2025, n=$n counties)",
    xlabel = "Number of clusters K",
    ylabel = "Posterior probability",
    legend = :topright,
    xticks = k_all,
)
for (i, r) in enumerate(pois_results)
    p_k = [mean(r.k .== k) for k in k_all]
    plot!(p_pois_k, k_all, p_k;
          label=r.label, color=pois_colors[i], linestyle=pois_styles[i],
          linewidth=(i==1 ? 3 : 1.5), marker=:circle, markersize=4)
end

# K trace plots (post burn-in)
p_trace = plot(
    title  = "K trace (post burn-in)",
    xlabel = "Iteration",
    ylabel = "K",
    legend = :topright,
)
all_colors  = [:black, :steelblue, :darkorange, :forestgreen, :purple, :crimson]
all_styles  = [:solid, :dash, :dash, :dash, :dot, :dot]
for (i, r) in enumerate(results)
    plot!(p_trace, r.k;
          label=r.label, color=all_colors[i], linestyle=all_styles[i],
          alpha=0.6, linewidth=(i∈[1,5] ? 1.5 : 0.8))
end

fig = plot(p_nb_k, p_pois_k, p_trace; layout=(1, 3), size=(1800, 500), margin=8Plots.mm)
out_path = joinpath(@__DIR__, "nrm_county_analysis.png")
savefig(fig, out_path)
println("\nPlot saved to $out_path")
display(fig)

# ============================================================================
# Save chains
# ============================================================================

results_dir = joinpath(dirname(@__DIR__), "results", "nrm_county_analysis")
mkpath(results_dir)

for r in results
    fname = replace(lowercase(r.label), r"[^a-z0-9]+" => "_") * ".jld2"
    fpath = joinpath(results_dir, fname)
    samples = r.samples
    k_post  = r.k
    @save fpath samples k_post
    println("Saved $(r.label) -> $fpath")
end
