# ============================================================================
# nrm_county_analysis.jl
#
# Compare NBPopulationRatesMarg / NBPopulationRates and
# PoissonPopulationRatesMarg / PoissonPopulationRates under several RJMCMC
# proposal combinations on the UK National Referral Mechanism (NRM) Q3 2025
# county-level dataset.
#
# Data source: data/nrm_county_data.csv (generated by prepare_nrm_county_data.py)
#   74 UK historic counties with referral counts + population denominators
#   and five deprivation domain covariates (IMD/WIMD/SIMD/NIMDM, normalised).
#
# Usage:
#   julia --project scripts/nrm_county_analysis.jl           # full run
#   julia --project scripts/nrm_county_analysis.jl --test    # 200 iterations
# ============================================================================

using DDCRP
using CSV, DataFrames, Distances
using Statistics, StatsBase, LinearAlgebra
using MultivariateStats
using Random
using Printf
using JLD2
using StatsPlots, Plots

Random.seed!(42)

# ============================================================================
# Load data
# ============================================================================

data_path = joinpath(dirname(@__DIR__), "data", "nrm_county_data.csv")
df = CSV.read(data_path, DataFrame)

y = Int.(df.referrals)          # fully observed — no missing
P = Int.(df.population)

covariate_cols = [:income, :employment, :education, :health, :crime]
X     = Float64.(Matrix(df[:, covariate_cols]))
X_std = (X .- mean(X, dims=1)) ./ std(X, dims=1)
D     = pairwise(Euclidean(), X_std', dims=2)
n     = length(y)

@printf("Dataset: %d counties, referrals %d–%d, population %d–%d\n",
        n, minimum(y), maximum(y), minimum(P), maximum(P))

# ============================================================================
# PCA plot: counties in covariate PC space, coloured by referral rate
# ============================================================================

rate = y ./ P

pca_model = fit(PCA, X_std'; maxoutdim=2)
PCs       = MultivariateStats.transform(pca_model, X_std')'   # (n × 2)

pev = principalvars(pca_model) ./ tvar(pca_model) .* 100

p_pca = scatter(
    PCs[:, 1], PCs[:, 2];
    zcolor      = rate,
    color       = :viridis,
    colorbar_title = "Referral rate (y/P)",
    marker      = :circle,
    markersize  = 6,
    markerstrokewidth = 0.5,
    label       = nothing,
    xlabel      = @sprintf("PC1 (%.1f%% var)", pev[1]),
    ylabel      = @sprintf("PC2 (%.1f%% var)", pev[2]),
    title       = "Counties in covariate PC space\n(NRM Q3 2025, coloured by referral rate)",
    size        = (700, 550),
    margin      = 8Plots.mm,
)

pca_path = joinpath(@__DIR__, "nrm_county_pca.png")
savefig(p_pca, pca_path)
println("PCA plot saved to $pca_path")
display(p_pca)

p_pc1_rate = scatter(
    PCs[:, 1], rate;
    marker            = :circle,
    markersize        = 6,
    markerstrokewidth = 0.5,
    label             = nothing,
    xlabel            = @sprintf("PC1 (%.1f%% var)", pev[1]),
    ylabel            = "Referral rate (y/P)",
    title             = "PC1 vs referral rate\n(NRM Q3 2025)",
    size              = (650, 480),
    margin            = 8Plots.mm,
)

pc1_rate_path = joinpath(@__DIR__, "nrm_county_pc1_rate.png")
savefig(p_pc1_rate, pc1_rate_path)
println("PC1 vs rate plot saved to $pc1_rate_path")
display(p_pc1_rate)

# ============================================================================
# Shared settings
# ============================================================================

test_mode = "--test" in ARGS
if test_mode
    println("Running in test mode (small iteration count).")
end

ddcrp_params = DDCRPParams(1.0, 1.0, 1.0, 0.1, 1.0, 0.1)

# NB priors
γ_a, γ_b = 1.0, 0.5
r_a, r_b  = 2.0, 0.5
# Poisson priors
ρ_a, ρ_b  = 1.0, 1.0

n_samples = test_mode ? 200 : 100_000
burn      = div(n_samples, 5)

base_opts = MCMCOptions(
    n_samples    = n_samples,
    verbose      = false,
    infer_params = Dict(
        :s_ddcrp  => false,
        :r        => true,
        :α_ddcrp  => true,
    ),
)

# ============================================================================
# Define proposals
# ============================================================================

proposals = [
    # --- Negative Binomial ---
    (
        label     = "NB Marg (Gibbs)",
        model     = NBPopulationRatesMarg(),
        priors    = NBPopulationRatesMargPriors(γ_a, γ_b, r_a, r_b),
        birth     = ConjugateProposal(),
        fixed_dim = NoUpdate(),
    ),
    (
        label     = "NB Prior + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = PriorProposal(),
        fixed_dim = Resample(PriorProposal()),
    ),
    (
        label     = "NB LogNormalMM + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = LogNormalMomentMatch(1.0),
        fixed_dim = Resample(PriorProposal()),
    ),
    (
        label     = "NB IGammaMM + Resample",
        model     = NBPopulationRates(),
        priors    = NBPopulationRatesPriors(γ_a, γ_b, r_a, r_b),
        birth     = InverseGammaMomentMatch(),
        fixed_dim = Resample(PriorProposal()),
    ),
    # --- Poisson ---
    (
        label     = "Pois Marg (Gibbs)",
        model     = PoissonPopulationRatesMarg(),
        priors    = PoissonPopulationRatesMargPriors(ρ_a, ρ_b),
        birth     = ConjugateProposal(),
        fixed_dim = NoUpdate(),
    ),
    (
        label     = "Pois Prior + Resample",
        model     = PoissonPopulationRates(),
        priors    = PoissonPopulationRatesPriors(ρ_a, ρ_b),
        birth     = PriorProposal(),
        fixed_dim = Resample(PriorProposal()),
    ),
]

# ============================================================================
# Run all proposals
# ============================================================================

results = []

for prop in proposals
    println("\n--- $(prop.label) ---")
    flush(stdout)

    samples, _ = mcmc(prop.model, y, P, D, ddcrp_params, prop.priors, prop.birth;
                      fixed_dim_proposal=prop.fixed_dim, opts=base_opts)

    k_post = calculate_n_clusters(samples.c[(burn+1):end, :])
    push!(results, (label=prop.label, k=k_post, samples=samples))
end

# ============================================================================
# Print posterior P(K) table
# ============================================================================

k_all = sort(unique(vcat([r.k for r in results]...)))

println("\n")
println("=== Posterior P(K) by proposal ===")
println()

k_cols    = join([@sprintf("  K=%-3d", k) for k in k_all])
col_header = @sprintf("%-32s", "Proposal") * k_cols * @sprintf("  %s  %s", "Mean K", "Mode K")
println(col_header)
println(repeat("-", length(col_header)))

for r in results
    k_probs = join([@sprintf("  %-5.3f", mean(r.k .== k)) for k in k_all])
    println(@sprintf("%-32s", r.label) * k_probs *
            @sprintf("  %-6.2f  %-6d", mean(r.k), mode(r.k)))
end

# ============================================================================
# Print and plot MAP cluster assignments
# ============================================================================

county_names = df.county

for r in results
    c_post = r.samples.c[(burn+1):end, :]
    z_map  = point_estimate_clustering(c_post; method=:MAP)
    k_map  = maximum(z_map)

    println("\n=== MAP clustering: $(r.label) (K=$k_map) ===")
    for k in 1:k_map
        members = county_names[z_map .== k]
        println(@sprintf("  Cluster %2d (%2d counties): %s", k, length(members),
                         join(members, ", ")))
    end
end

# Add z_map to each result
results = [merge(r, (z_map=point_estimate_clustering(
    r.samples.c[(burn+1):end, :]; method=:MAP),)) for r in results]

# Write MAP assignments to CSV for the Python geography map script
map_asgn_path = joinpath(dirname(@__DIR__), "results", "nrm_county_analysis", "map_assignments.csv")
open(map_asgn_path, "w") do io
    println(io, "county,proposal,cluster")
    for r in results
        for (i, county) in enumerate(county_names)
            println(io, "\"$(county)\",\"$(r.label)\",$(r.z_map[i])")
        end
    end
end
println("MAP assignments written to $map_asgn_path")

# Heatmap-style grid: proposals × counties, colour = cluster label
n_props  = length(results)
max_k    = maximum(maximum(r.z_map) for r in results)
asgn_mat = hcat([r.z_map for r in results]...)'   # (n_props × n_counties)

# Sort counties by MAP cluster of first (Gibbs NB) result for visual coherence
sort_idx  = sortperm(results[1].z_map)
asgn_sort = asgn_mat[:, sort_idx]
county_sort = county_names[sort_idx]

p_map = heatmap(
    asgn_sort,
    yticks  = (1:n_props, [r.label for r in results]),
    xticks  = (1:5:n, county_sort[1:5:end]),
    xrotation = 45,
    title   = "MAP cluster assignments\n(NRM Q3 2025, sorted by NB Marg cluster)",
    xlabel  = "County",
    ylabel  = "Proposal",
    color   = :tab10,
    clims   = (1, max(max_k, 10)),
    colorbar_title = "Cluster",
    size    = (1400, 400),
    margin  = 10Plots.mm,
    yflip   = false,
)

map_path = joinpath(@__DIR__, "nrm_county_map_assignments.png")
savefig(p_map, map_path)
println("\nMAP assignments heatmap saved to $map_path")
display(p_map)

# PC-space scatter coloured by MAP cluster — one panel per proposal
cluster_colors = [:black, :steelblue, :darkorange, :forestgreen,
                  :purple, :crimson, :teal, :gold, :hotpink, :gray]

pca_panels = [
    scatter(
        PCs[:, 1], PCs[:, 2];
        zcolor            = r.z_map,
        color             = :tab10,
        clims             = (1, max(maximum(r.z_map), 10)),
        colorbar          = false,
        marker            = :circle,
        markersize        = 5,
        markerstrokewidth = 0.5,
        label             = nothing,
        title             = r.label,
        xlabel            = "PC1",
        ylabel            = "PC2",
    )
    for r in results
]

p_pca_map = plot(pca_panels...;
    layout = (2, div(n_props + 1, 2)),
    size   = (300 * div(n_props + 1, 2), 550),
    margin = 6Plots.mm,
    plot_title = "MAP cluster assignments in covariate PC space\n(NRM Q3 2025)",
)

pca_map_path = joinpath(@__DIR__, "nrm_county_pca_map.png")
savefig(p_pca_map, pca_map_path)
println("PCA MAP plot saved to $pca_map_path")
display(p_pca_map)

# PC1 vs referral rate, coloured by MAP cluster — one panel per proposal
pc1_rate_panels = [
    scatter(
        PCs[:, 1], rate;
        zcolor            = r.z_map,
        color             = :tab10,
        clims             = (1, max(maximum(r.z_map), 10)),
        colorbar          = false,
        marker            = :circle,
        markersize        = 5,
        markerstrokewidth = 0.5,
        label             = nothing,
        title             = r.label,
        xlabel            = "PC1",
        ylabel            = "Referral rate (y/P)",
    )
    for r in results
]

p_pc1_rate_map = plot(pc1_rate_panels...;
    layout     = (2, div(n_props + 1, 2)),
    size       = (300 * div(n_props + 1, 2), 550),
    margin     = 6Plots.mm,
    plot_title = "PC1 vs referral rate, coloured by MAP cluster\n(NRM Q3 2025)",
)

pc1_rate_map_path = joinpath(@__DIR__, "nrm_county_pc1_rate_map.png")
savefig(p_pc1_rate_map, pc1_rate_map_path)
println("PC1 vs rate MAP plot saved to $pc1_rate_map_path")
display(p_pc1_rate_map)

# ============================================================================
# Geography map via Python (geopandas choropleth)
# ============================================================================

println("\nGenerating geography map ...")
map_script = joinpath(@__DIR__, "plot_nrm_map.py")
run(`uv run $map_script`)

# ============================================================================
# Plot: posterior P(K) for NB and Poisson separately + K trace plots
# ============================================================================

nb_results   = filter(r -> startswith(r.label, "NB"),   results)
pois_results = filter(r -> startswith(r.label, "Pois"), results)

nb_colors   = [:black, :steelblue, :darkorange, :forestgreen]
pois_colors = [:black, :steelblue]
nb_styles   = [:solid, :dash, :dash, :dash]
pois_styles = [:solid, :dash]

# P(K) — NB
p_nb_k = plot(
    title  = "Posterior P(K) — NB models\n(NRM Q3 2025, n=$n counties)",
    xlabel = "Number of clusters K",
    ylabel = "Posterior probability",
    legend = :topright,
    xticks = k_all,
)
for (i, r) in enumerate(nb_results)
    p_k = [mean(r.k .== k) for k in k_all]
    plot!(p_nb_k, k_all, p_k;
          label=r.label, color=nb_colors[i], linestyle=nb_styles[i],
          linewidth=(i==1 ? 3 : 1.5), marker=:circle, markersize=4)
end

# P(K) — Poisson
p_pois_k = plot(
    title  = "Posterior P(K) — Poisson models\n(NRM Q3 2025, n=$n counties)",
    xlabel = "Number of clusters K",
    ylabel = "Posterior probability",
    legend = :topright,
    xticks = k_all,
)
for (i, r) in enumerate(pois_results)
    p_k = [mean(r.k .== k) for k in k_all]
    plot!(p_pois_k, k_all, p_k;
          label=r.label, color=pois_colors[i], linestyle=pois_styles[i],
          linewidth=(i==1 ? 3 : 1.5), marker=:circle, markersize=4)
end

# K trace plots (post burn-in)
p_trace = plot(
    title  = "K trace (post burn-in)",
    xlabel = "Iteration",
    ylabel = "K",
    legend = :topright,
)
all_colors  = [:black, :steelblue, :darkorange, :forestgreen, :purple, :crimson]
all_styles  = [:solid, :dash, :dash, :dash, :dot, :dot]
for (i, r) in enumerate(results)
    plot!(p_trace, r.k;
          label=r.label, color=all_colors[i], linestyle=all_styles[i],
          alpha=0.6, linewidth=(i∈[1,5] ? 1.5 : 0.8))
end

fig = plot(p_nb_k, p_pois_k, p_trace; layout=(1, 3), size=(1800, 500), margin=8Plots.mm)
out_path = joinpath(@__DIR__, "nrm_county_analysis.png")
savefig(fig, out_path)
println("\nPlot saved to $out_path")
display(fig)

# ============================================================================
# Save chains
# ============================================================================

results_dir = joinpath(dirname(@__DIR__), "results", "nrm_county_analysis")
mkpath(results_dir)

for r in results
    fname = replace(lowercase(r.label), r"[^a-z0-9]+" => "_") * ".jld2"
    fpath = joinpath(results_dir, fname)
    samples = r.samples
    k_post  = r.k
    @save fpath samples k_post
    println("Saved $(r.label) -> $fpath")
end



plot(calculate_n_clusters(results[5].samples.c[(burn+1):end, :]))